name: ci

on:
  push:
    paths:
      - "**.c"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  windows-msvc:
    timeout-minutes: 5
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -Bbuild -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Test
      run: ctest --test-dir build -C Release -V

  windows-gcc:
    timeout-minutes: 5
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -Bbuild -G "MinGW Makefiles"

    - name: Build
      run: cmake --build build --parallel

    - name: Test
      run: ctest --test-dir build -V

  linux-mac:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    strategy:
      matrix:
        cxx: [g++, clang++]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -Bbuild
      env:
        CXX: ${{ matrix.cxx }}

    - name: Build
      run: cmake --build build --parallel

    - name: Test
      run: ctest --test-dir build -V
